<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HygiaTrade.Common\HygiaTrade.Common.csproj" />
    <ProjectReference Include="..\HygiaTrade.Core\HygiaTrade.Core.csproj" />
    <ProjectReference Include="..\HygiaTrade.Data\HygiaTrade.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>HygiaTrade.Domain</AssemblyName>
    <RootNamespace>HygiaTrade.Domain</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
